# Generated by Django 5.1.2 on 2024-10-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
