# Generated by Django 5.1 on 2024-10-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_delete_category_categories_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='listed',
            new_name='status',
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='edition',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='type1',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
