# Generated by Django 5.1 on 2024-10-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_listed_brand_status_brand_image_edition_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='status',
        ),
        migrations.AddField(
            model_name='categories',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
