# Generated by Django 5.1 on 2024-10-23 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_remove_product_price_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Variant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.variants'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.categories'),
        ),
    ]
