# Generated by Django 5.1 on 2024-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_brand_product_edition_type1_categories_variants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
    ]
