# Generated by Django 5.1 on 2024-10-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_categories_status_categories_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='is_listed',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='listed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='listed',
        ),
        migrations.RemoveField(
            model_name='type1',
            name='listed',
        ),
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
        migrations.AddField(
            model_name='edition',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
        migrations.AddField(
            model_name='type1',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
    ]
