# Generated by Django 5.1 on 2024-10-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_remove_brand_cropped_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type1',
            old_name='count_of_type',
            new_name='Quantity',
        ),
    ]
