# Generated by Django 5.1 on 2024-10-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_type1_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
    ]
