# Generated by Django 5.1 on 2024-10-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_edition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
