# Generated by Django 5.1 on 2024-10-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_product_variant_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Variant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.variants'),
        ),
    ]
