# Generated by Django 5.1 on 2024-10-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_product_category'),
        ('management', '0030_alter_product_status'),
    ]

    operations = [
    ]
