# Generated by Django 5.1 on 2024-10-25 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_auto_20241024_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/p.png', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.categories'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='variants',
            name='stock',
            field=models.JSONField(),
        ),
    ]
