# Generated by Django 5.2.5 on 2025-11-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_product_main_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.ManyToManyField(blank=True, related_name='products_in_edition', to='management.edition'),
        ),
        migrations.AddField(
            model_name='product',
            name='type1',
            field=models.ManyToManyField(blank=True, related_name='products_in_type', to='management.type1'),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='products_in_variant', to='management.variants'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
