# Generated by Django 5.1 on 2024-10-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_categories_is_listed_remove_edition_listed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
