# Generated by Django 5.1 on 2024-10-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_brand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='media/images/default.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='edition',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='type1',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
