# Generated by Django 5.1 on 2024-10-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_sportscar_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cropped_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/cropped/'),
        ),
    ]
