# Generated by Django 5.1 on 2024-10-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_brand_cropped_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
    ]
