# Generated by Django 5.1 on 2024-10-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_brand_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cropped_image',
        ),
    ]
