# Generated by Django 5.1 on 2024-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_rename_count_of_type_type1_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type1',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
    ]
