# Generated by Django 5.1 on 2024-10-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.CharField(default='listed', max_length=10),
        ),
    ]
