# Generated by Django 5.1 on 2024-10-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.variants'),
        ),
    ]
