# Generated by Django 5.1 on 2024-10-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_remove_variants_image_variants_image1_and_more'),
    ]

    operations = [
    ]
