# Generated by Django 5.2.5 on 2025-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_remove_product_category_remove_variants_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Residential', 'Residential Design'), ('Commercial', 'Commercial Spaces'), ('Hospitality', 'Hospitality Design'), ('Space Planning', 'Space Planning'), ('Color Consultation', 'Color Consultation'), ('Furniture Selection', 'Furniture Selection')], max_length=100)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_duration', models.IntegerField(help_text='Duration in weeks')),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='One feature per line')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100)),
                ('image', models.ImageField(upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='type1',
            name='products',
        ),
        migrations.DeleteModel(
            name='SportsCar',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Type1',
        ),
    ]
