# Generated by Django 5.2.5 on 2025-11-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_services_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project Images',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('residential', 'Residential Design'), ('commercial', 'Commercial Design'), ('hospitality', 'Hospitality Design'), ('retail', 'Retail Design'), ('office', 'Office Design')], max_length=50)),
                ('overview', models.TextField()),
                ('client_field', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('area', models.CharField(help_text='e.g., 3,500 sq ft', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 6 Months', max_length=100)),
                ('budget', models.CharField(help_text='e.g., $120K', max_length=100)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=200)),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('feature1_title', models.CharField(blank=True, max_length=200)),
                ('feature1_desc', models.TextField(blank=True)),
                ('feature2_title', models.CharField(blank=True, max_length=200)),
                ('feature2_desc', models.TextField(blank=True)),
                ('feature3_title', models.CharField(blank=True, max_length=200)),
                ('feature3_desc', models.TextField(blank=True)),
                ('feature4_title', models.CharField(blank=True, max_length=200)),
                ('feature4_desc', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True, help_text='Comma separated tags', max_length=500)),
                ('testimonial', models.TextField(blank=True)),
                ('hero_image', models.ImageField(upload_to='projects/hero/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_images', models.ManyToManyField(blank=True, related_name='projects', to='management.projectimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
