# Generated by Django 5.2.5 on 2025-11-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_alter_contactform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='replay_message',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='replied_date',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactform',
            name='budget',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, default='rabi@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(default='rabi', max_length=100),
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(default='rabii', max_length=100),
        ),
        migrations.AddField(
            model_name='contactform',
            name='project_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactform',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactform',
            name='timeline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
