# Generated by Django 5.2.5 on 2025-11-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_remove_contactform_replay_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='replied_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('replied', 'Replied')], default='new', max_length=20),
        ),
    ]
